<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
		<!--<GameDir>$(APPDATA)\raicuparta\rai-pal\data\installed-mods\8148729079362356270\bepinex\BepInEx\plugins\</GameDir>-->
		<GameDir>Y:\SteamLibrary\steamapps\common\New Star GP\release\BepInEx\plugins\</GameDir>		
    </PropertyGroup>     
    <Target Name="CreateAndCopyToGameDir" AfterTargets="Build">
        <MakeDir Directories="$(GameDir)$(TargetName)" Condition="!Exists('$(GameDir)$(TargetName)')" />
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GameDir)$(TargetName)" />
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(GameDir)$(TargetName)" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
        <Message Text="[$(ProjectName)] Copied $(TargetName).dll and $(TargetDir)$(TargetName).pdb  to $(GameDir)$(TargetName)" Importance="High" />
    </Target>
</Project>